### PR TITLE
Programmer net proposal

### PR DESCRIPTION
**Pull request by iaroslav-ai**
Somewhat far fetched, but maybe in some very simple setup already doable (e.g. learning to program hello world).

### CODE REVIEW

**Comment by iaroslav-ai** [comment]
Maybe a bit too abstract; If so let me know.

**Comment by ilyasu123** [comment]
Try limiting the scope of the problem.  As presently stated, it is too broad and too hard.  It will be much more useful to say, "here is a link to a text - program dataset, please try to get the greatest accuracy on it", and the dataset should be pretty simple, or else the problem will be totally unsolvable.   In short, try to narrow the scope to make it barely solvable.

**Comment by ethancaballero** [comment]
just noticed that pull I just requested is similar to this one

**Comment by yanjon** [comment]
A recent DeepMind paper http://arxiv.org/abs/1603.06744 proposed a generative model for code generation.

**Comment by ethancaballero** [comment]
It's linked to in the description of paper2code research request

**Comment by iaroslav-ai** [comment]
@yanjon thanks for the reference!
@ethancaballero indeed it is similar, yours is much more detailed though.  
@ilyasu123 agreed. I will close this pull, and open a new one as soon as I will have something more solvable and concrete and different from what @ethancaballero proposes.

**Pull request closed without merging**
